apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgadmin-data
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: pgadmin
    app.kubernetes.io/component: admin-ui
    app.kubernetes.io/part-of: postgresql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
