apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallabag
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: wallabag-gitops/app
  destination:
    server: https://kubernetes.default.svc
    namespace: wallabag
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
