# grafana-only-values.yaml
# Grafana only

grafana:
  enabled: true
  
  # Admin password (CHANGE THIS!)
  adminPassword: "openebs-admin-secure-password"

  # Persistence using balanced Mayastor for dashboard data
  persistence:
    enabled: true
    storageClassName: mayastor-monitoring-balanced # 2 replicas for good availability
    size: 10Gi
    accessModes:
      - ReadWriteOnce

  # Resources
  resources:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

  # Service configuration for MetalLB
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000 # Internal Grafana port
    annotations:
      metallb.universe.tf/loadBalancerIPs: "192.168.0.201"

  # Grafana configuration
  grafana.ini:
    server:
      root_url: "http://grafana.verticon.com/"
      serve_from_sub_path: false
      domain: "grafana.verticon.com"
    security:
      allow_embedding: true
    auth.anonymous:
      enabled: true
      org_role: Viewer
    # Database and cleanup settings to prevent disk space issues
    database:
      log_queries: false
      max_idle_conn: 2
      max_open_conn: 10
    log:
      mode: console
      level: warn
    # Prevent excessive disk usage from temporary files
    paths:
      temp_data_lifetime: 24h

  # Datasource configuration for split monitoring stack
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: "Prometheus"
          type: prometheus
          uid: prometheus
          url: http://prometheus-kube-prometheus-prometheus.monitoring:80/
          access: proxy
          isDefault: true
          jsonData:
            httpMethod: POST
            timeInterval: 30s
        - name: "Alertmanager"
          type: alertmanager
          uid: alertmanager
          url: http://alertmanager-kube-promethe-alertmanager.monitoring:9093/
          access: proxy
          jsonData:
            handleGrafanaManagedAlerts: false
            implementation: prometheus

  # Sidecar configuration to automatically discover dashboard ConfigMaps
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      labelValue: "1"
      folder: /tmp/dashboards
      searchNamespace: monitoring
      provider:
        foldersFromFilesStructure: true
    datasources:
      enabled: false

# Disable all other components
prometheus:
  enabled: false
prometheusOperator:
  enabled: false
alertmanager:
  enabled: false
nodeExporter:
  enabled: false
kubeStateMetrics:
  enabled: false

# No default rules needed for Grafana only
defaultRules:
  create: false

# Global configuration
global:
  rbac:
    create: true
    pspEnabled: false