apiVersion: v1
kind: Service
metadata:
  name: rook-ceph-rgw-external
  namespace: rook-ceph
  labels:
    app: rook-ceph-rgw
    rook_cluster: rook-ceph
    rook_object_store: rook-ceph-rgw
  annotations:
    # MetalLB will use this IP from the address pool
    metallb.universe.tf/address-pool: default
spec:
  type: LoadBalancer
  # Fixed IP for S3 endpoint
  loadBalancerIP: 192.168.0.210

  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  # Uncomment for HTTPS
  # - name: https
  #   port: 443
  #   protocol: TCP
  #   targetPort: 443

  selector:
    app: rook-ceph-rgw
    rook_object_store: rook-ceph-rgw

  # Preserve client source IP
  externalTrafficPolicy: Cluster

  sessionAffinity: None
