apiVersion: apps/v1
kind: Deployment
metadata:
  name: rssbridge
  namespace: rssbridge
  labels:
    app.kubernetes.io/name: rssbridge
    app.kubernetes.io/component: app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: rssbridge
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rssbridge
        app.kubernetes.io/component: app
    spec:
      enableServiceLinks: false
      containers:
        - name: rssbridge
          image: rssbridge/rss-bridge:latest
          ports:
            - containerPort: 80
              name: http
          volumeMounts:
            - name: config
              mountPath: /config/config.ini.php
              subPath: config.ini.php
            - name: cache
              mountPath: /var/cache/rssbridge
      volumes:
        - name: config
          configMap:
            name: rssbridge-config
        - name: cache
          persistentVolumeClaim:
            claimName: rssbridge-cache
