apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rssbridge-cache
  namespace: rssbridge
  labels:
    app.kubernetes.io/name: rssbridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rook-ceph-block
  resources:
    requests:
      storage: 1Gi
