---
# ServiceMonitor for PostgreSQL cluster metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgresql-cluster-metrics
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: postgresql
    release: prometheus  # Must match Prometheus selector
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: production-postgresql
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics

---
# ServiceMonitor for CloudNativePG operator metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cnpg-operator-metrics
  namespace: cnpg-system
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/component: operator
    release: prometheus  # Must match Prometheus selector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics