---
# PodMonitor for PostgreSQL cluster metrics (CloudNativePG automatically creates PodMonitor when enablePodMonitor: true)
# This will be created automatically by CloudNativePG operator

---
# ServiceMonitor for CloudNativePG operator metrics
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cnpg-operator-metrics
  namespace: cnpg-system
  labels:
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/component: operator
    release: prometheus  # Must match Prometheus selector
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudnative-pg
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics