apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-stack-grafana
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mayastor-monitoring-balanced
