# openebs-prometheusrules.yaml
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: openebs-alerts
  namespace: monitoring
  labels:
    release: prometheus-stack
spec:
  groups:
    - name: openebs.rules
      rules:
        - alert: MayastorDiskpoolHigh
          expr: (diskpool_used_size_bytes / diskpool_total_size_bytes) * 100 > 80
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Mayastor diskpool usage is high"
            description: "Diskpool {{ $labels.name }} on node {{ $labels.node }} usage is above 80%"

        - alert: MayastorDiskpoolCritical
          expr: (diskpool_used_size_bytes / diskpool_total_size_bytes) * 100 > 85
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Mayastor diskpool usage is critically high"
            description: "Diskpool {{ $labels.name }} on node {{ $labels.node }} usage is above 85%"

        - alert: OpenEBSComponentDown
          expr: up{job=~"openebs-.*"} == 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "OpenEBS component is down"
            description: "OpenEBS component {{ $labels.job }} is down"
