apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cosmo-router
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: cosmo-gitops
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: cosmo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: ""
      kind: ConfigMap
      name: cosmo-router-json
      namespace: cosmo
      jsonPointers:
        - /data/router.json
