apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers: [] # Explicitly empty
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: 8.1.1
    helm:
      values: |
        global:
          domain: argocd.verticon.com

        server:
          insecure: true
          ingress:
            enabled: false
          service:
            type: LoadBalancer
          extraArgs:
            - --insecure

        notifications:
          enabled: false
        dex:
          enabled: false
        redis-ha:
          enabled: false
        redis:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
