apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kured
  namespace: argocd
spec:
  project: default

  sources:
    - chart: kured
      repoURL: https://kubereboot.github.io/charts
      targetRevision: 5.5.1
      helm:
        valueFiles:
          - $values/kured-gitops/helm/kured-values.yaml

    - repoURL: https://github.com/jconlon/ops-microk8s
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
