# This is experimental and not deployed at this time.
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mayastor-diskpools
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    path: openebs-gitops/diskpools
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
