apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: postgresql-gitops/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true