---
# Primary PostgreSQL service (read/write)
apiVersion: v1
kind: Service
metadata:
  name: postgresql-primary
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: primary
    app.kubernetes.io/part-of: postgresql
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.210"
spec:
  type: LoadBalancer
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    cnpg.io/cluster: production-postgresql
    cnpg.io/instanceRole: primary

---
# Read-only PostgreSQL service (read replicas)
apiVersion: v1
kind: Service
metadata:
  name: postgresql-readonly
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: readonly
    app.kubernetes.io/part-of: postgresql
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.0.211"
spec:
  type: LoadBalancer
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    cnpg.io/cluster: production-postgresql
    cnpg.io/instanceRole: replica

---
# Internal service for cluster communication
apiVersion: v1
kind: Service
metadata:
  name: postgresql-cluster
  namespace: postgresql-system
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/component: cluster
    app.kubernetes.io/part-of: postgresql
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    cnpg.io/cluster: production-postgresql