apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freshrss-database
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: freshrss/database
  destination:
    server: https://kubernetes.default.svc
    namespace: postgresql-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
