apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: apicurio-registry
  namespace: apicurio-registry
spec:
  deployment:
    managedResources:
      disableIngress: true
  configuration:
    persistence: sql
    sql:
      dataSource:
        url: jdbc:postgresql://production-postgresql-rw.postgresql-system.svc.cluster.local:5432/apicurio
        userName: apicurio
    env:
      - name: REGISTRY_DATASOURCE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: apicurio-db-credentials
            key: password
