apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: app-backup-user
  namespace: rook-ceph
  labels:
    app: application-backup
spec:
  store: rook-ceph-rgw
  displayName: "Application Backup Service"

  # Quotas for application backups
  quotas:
    maxBuckets: 10          # More buckets for multiple apps
    maxSize: "1Ti"          # 1TB for app backups
    maxObjects: 500000      # Maximum objects

  # Capabilities (optional - defaults to full access)
  # capabilities:
  #   user: "*"
  #   bucket: "*"

---
# Secret will be auto-created with credentials:
# - AccessKey: kubectl get secret app-backup-user -n rook-ceph -o jsonpath='{.data.AccessKey}' | base64 -d
# - SecretKey: kubectl get secret app-backup-user -n rook-ceph -o jsonpath='{.data.SecretKey}' | base64 -d
