# mayastor-storage-classes.yaml
# Dedicated storage classes for monitoring infrastructure

---
# High-performance storage class for Prometheus (3 replicas for HA)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-monitoring-ha
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: io.openebs.csi-mayastor
parameters:
  # High performance settings for metrics storage
  fsType: ext4
  protocol: nvmf
  repl: "3" # 3 replicas for high availability
  ioTimeout: "30" # 30 second I/O timeout
  thin: "false" # Thick provisioning for consistent performance
volumeBindingMode: WaitForFirstConsumer # Better pod scheduling
allowVolumeExpansion: true
reclaimPolicy: Retain # Retain for monitoring data safety

---
# Balanced storage class for Grafana and AlertManager (2 replicas)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-monitoring-balanced
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: io.openebs.csi-mayastor
parameters:
  fsType: ext4
  protocol: nvmf
  repl: "2" # 2 replicas for good availability
  ioTimeout: "30"
  thin: "true" # Thin provisioning for efficient space usage
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain

---
# Fast single-replica class for temporary/cache data
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-monitoring-fast
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: io.openebs.csi-mayastor
parameters:
  fsType: ext4
  protocol: nvmf
  repl: "1" # Single replica for maximum performance
  ioTimeout: "10" # Shorter timeout for fast response
  thin: "false" # Thick provisioning for consistent performance
volumeBindingMode: Immediate # Immediate binding for fast provisioning
allowVolumeExpansion: true
reclaimPolicy: Delete

---
# Optional: Storage class with local preference for specific workloads
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mayastor-monitoring-local
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: io.openebs.csi-mayastor
parameters:
  fsType: ext4
  protocol: nvmf
  repl: "1"
  ioTimeout: "30"
  thin: "true"
  # Optional: Add local preference if you have specific node requirements
  # local: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
