apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"  # Deploy after storage is ready
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: openebs-gitops/monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true