apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-storageclasses
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"  # Deploy after diskpools
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: openebs-gitops/storageclasses
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true