apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs-diskpools
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after Mayastor
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: openebs-gitops/diskpools
  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true