project: dot
providers:
  google_secretmanager:
    env:
      WALLABAG_DB_PASSWORD:
        path: projects/1000827005146/secrets/wallabag-db-password/versions/latest
      WALLABAG_SECRET_KEY:
        path: projects/1000827005146/secrets/wallabag-secret-key/versions/latest
      WALLABAG_ROLE_PASSWORD:
        path: projects/1000827005146/secrets/wallabag-db-password/versions/latest
