apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls
  namespace: kgateway-system
spec:
  secretName: grafana-tls
  dnsNames:
    - grafana.verticon.com
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
