apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jellyfin-tls
  namespace: kgateway-system
spec:
  secretName: jellyfin-tls
  dnsNames:
    - jellyfin.verticon.com
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
