apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kagent-tls
  namespace: kgateway-system
spec:
  secretName: kagent-tls
  dnsNames:
    - kagent.verticon.com
  issuerRef:
    name: letsencrypt-http01
    kind: ClusterIssuer
