apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://openebs.github.io/charts
    chart: openebs
    targetRevision: 3.7.0
    helm:
      values: |-
        mayastor:
          enabled: true
          csi:
            node:
              kubeletDir: "/var/snap/microk8s/common/var/lib/kubelet"

  destination:
    server: https://kubernetes.default.svc
    namespace: openebs
