apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-storageclasses
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default

  source:
    repoURL: https://github.com/jconlon/ops-microk8s.git
    targetRevision: main
    path: rook-ceph/storageclasses

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
