apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rook-ceph-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  source:
    # Rook Helm chart repository
    chart: rook-ceph
    repoURL: https://charts.rook.io/release
    targetRevision: v1.15.8

    helm:
      # Reference to values file in Git
      valueFiles:
        - $values/rook-ceph/helm/rook-operator-values.yaml

  # Additional source for values files from Git
  sources:
    - chart: rook-ceph
      repoURL: https://charts.rook.io/release
      targetRevision: v1.15.8
      helm:
        valueFiles:
          - $values/rook-ceph/helm/rook-operator-values.yaml

    - repoURL: https://github.com/jconlon/ops-microk8s.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

  ignoreDifferences:
    - group: ""
      kind: Secret
      name: rook-ceph-admission-controller
      jsonPointers:
        - /data
