apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi-kafka-operator
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default

  sources:
    - chart: strimzi-kafka-operator
      repoURL: https://strimzi.io/charts/
      targetRevision: 0.44.0
      helm:
        valueFiles:
          - $values/kafka-gitops/helm/strimzi-operator-values.yaml

    - repoURL: https://github.com/jconlon/ops-microk8s
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: kafka-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
