apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-resources
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: kagent-gitops/resources
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
