# OpenEBS Mayastor Helm Values File
# This configuration enables Mayastor while disabling other OpenEBS engines and NATS
# Updated for MicroK8s compatibility with correct kubelet path

# Global OpenEBS settings
global:
  # Set to true to enable debug logging
  debug: false
  # Image registry settings
  imageRegistry: ""
  imagePullSecrets: []

# Mayastor configuration
mayastor:
  # Enable Mayastor engine
  enabled: true
  io_engine:
    # IO Engine configuration - Fix for IOVA mode
    # Pass additional arguments to the Environment Abstraction Layer
    envcontext: "iova-mode=pa"

  # CSI configuration with MicroK8s kubelet path
  csi:
    node:
      kubeletDir: /var/snap/microk8s/common/var/lib/kubelet
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
      securityContext:
        privileged: true
        runAsUser: 0
        runAsNonRoot: false
        allowPrivilegeEscalation: true
        capabilities:
          add:
            - SYS_ADMIN
            - DAC_OVERRIDE
            - SYS_CHROOT
            - MKNOD
        seLinuxOptions:
          type: spc_t
      nodeSelector: {}
      tolerations: []
      affinity: {}
      hostNetwork: true
      hostPID: true

  # Mayastor Control Plane
  controlPlane:
    replicaCount: 1

    # Resource limits for control plane
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    # Node selector for control plane
    nodeSelector: {}

    # Tolerations for control plane
    tolerations: []

    # Affinity for control plane
    affinity: {}

  # Mayastor Data Plane
  dataPlane:
    # Resource limits for data plane
    resources:
      limits:
        cpu: 1000m
        memory: 1Gi
        hugepages-2Mi: 2Gi
      requests:
        cpu: 500m
        memory: 512Mi
        hugepages-2Mi: 2Gi

    # Node selector for data plane (only nodes with Mayastor label)
    nodeSelector:
      openebs.io/engine: mayastor

    # Tolerations for data plane
    tolerations: []

    # Affinity for data plane
    affinity: {}

  # CSI Controller
  csiController:
    replicaCount: 1

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi

    nodeSelector: {}
    tolerations: []
    affinity: {}

  # Service configuration
  service:
    type: ClusterIP
    port: 10124

  # Storage class configuration
  storageClass:
    enabled: true
    name: mayastor
    isDefaultClass: false
    reclaimPolicy: Delete
    allowVolumeExpansion: true
    volumeBindingMode: WaitForFirstConsumer # Better for pod scheduling
    parameters:
      repl: "3" # Updated to match your Prometheus storage class
      protocol: "nvmf" # Protocol to use (nvmf or iscsi)
      csi.storage.k8s.io/fstype: "ext4" # Updated parameter name (fixes deprecation warning)
    allowedTopologies: []

  # Monitoring and observability
  monitoring:
    enabled: true
    # Prometheus metrics endpoint
    prometheus:
      enabled: true
      port: 9090
      path: /metrics

  # Security context - Updated for MicroK8s compatibility
  securityContext:
    runAsNonRoot: false # Allow root execution
    # runAsUser: 1000     # Commented out for CSI compatibility
    # fsGroup: 2000       # Commented out for CSI compatibility

# Disable other OpenEBS engines to focus on Mayastor
# Local PV HostPath
localpv-hostpath:
  enabled: false

# Local PV Device
localpv-device:
  enabled: false

# Local PV LVM
localpv-lvm:
  enabled: false

# Local PV ZFS
localpv-zfs:
  enabled: false

# Dynamic Local PV
dynamic-localpv:
  enabled: false

# Jiva
jiva:
  enabled: false

# cStor
cstor:
  enabled: false

# OpenEBS NDM (Node Device Manager)
# Keep enabled as Mayastor may use it for device discovery
ndm:
  enabled: true

  # NDM configuration
  filters:
    enableOsDiskExcludeFilter: true
    enableVendorFilter: true
    enablePartitionFilter: true
    excludeVendors: "CLOUDBYT,OpenEBS"
    excludePaths: "loop,fd0,sr0,/dev/ram,/dev/dm-,/dev/md,/dev/rbd,/dev/zd"

  # Probe configuration
  probes:
    enableSeachest: false
    enableUdevProbe: true
    enableSmartProbe: true

  # Node selector for NDM
  nodeSelector: {}

  # Tolerations for NDM
  tolerations: []

  # Resources for NDM
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# NDM Operator
ndmOperator:
  enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# OpenEBS API Server (optional)
apiserver:
  enabled: false

# OpenEBS Admission Server (optional)
admission-server:
  enabled: false

# Snapshot Controller (optional but recommended)
snapshot-controller:
  enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi

# CRD configuration
crds:
  csi:
    volumeSnapshots:
      enabled: true

# EXPLICITLY DISABLE NATS COMPONENTS
# Add these sections to disable NATS messaging components
nats:
  enabled: false

# If using older OpenEBS chart versions, also disable these
messaging:
  enabled: false
  nats:
    enabled: false

# Event exporter that might depend on NATS
eventExporter:
  enabled: false

# Webhook configurations that might use NATS
webhooks:
  enabled: false

# OpenEBS specific messaging components
openebs:
  messaging:
    enabled: false
  nats:
    enabled: false
  eventExporter:
    enabled: false

# Disable built-in MinIO
minio:
  enabled: false

# Configure Loki to use your existing MinIO
loki:
  enabled: true
  loki:
    storage_config:
      aws:
        endpoint: "http://trout:9000"
        access_key_id: "jackcondor"
        secret_access_key: "xidejc88wiix3"
        s3forcepathstyle: true
        bucketnames: "openebs-logs"
