apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/jconlon/ops-microk8s
    targetRevision: HEAD
    path: argo-workflows-gitops/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
